name: flutter_live_support
description: Flutter package to implement a firestore chat between customer and
  product support. This is a forked project from https://github.com/hwr12/flutter_live_support .
version: 1.0.0-alpha.0
homepage: https://github.com/hwr12/flutter_live_support
repository: https://github.com/hwr12/flutter_live_support
issue_tracker: https://github.com/hwr12/flutter_live_support/issues

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  cloud_firestore: '>=2.2.0 <4.0.0'
  firebase_core: '>=1.2.0 <2.0.0'
  flutter:
    sdk: flutter
  flutter_support_chat:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

false_secrets:
- example/web/index.html
- /example/android/app/google-services.json
- /lib/firebase_options.dart
